### ISSUE TITLE
error when change BasePath to testnet

### ISSUE THREAD

**Issue by anotar** [qct/bitmex-go#3]
Because i want to test my strategy, when i changed the BasePath in configuration.go from "https://www.bitmex.com/api/v1" to "https://testnet.bitmex.com/api/v1", and try running testBuy function in main.go,  the log printed like this:
{"error":{"message":"Signature not valid.","name":"HTTPError"}}
Please let me know how do i fix this error.
Also, there's a difference between main.go in the release ver 2.0.1 and the github lastest code, i don't know why there's difference.

**Comment by anotar** [comment]
You released ver 2.0.1 at Jan, but you fixed this problem last year.
now i really don't know what's going on.
i'm using ver 2.0.1 so i'll get the source code again but try with installing from github.

**Comment by anotar** [comment]
Lastly, i really appreciate you to make this project.

**Comment by qct** [comment]
@0xkardux  please use master branch to get latest code and don't hesitate to let me know if you have any problem.
